name: Exploring Variables and Secrets in Jobs

on:
    push

jobs:
    docker:
        env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: UserNameDockerRegistry
            IMAGE_NAME: github-actions-nginx
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

            - name: Docker Login
              env:
                  DOCKER_PASSWORD: UserPasswordOfRegistry
              run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

            - name: Docker Publish
              env:
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: UserNameDockerRegistry
                IMAGE_NAME: github-actions-nginx
              run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    deploy:
        env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: UserNameDockerRegistry
            IMAGE_NAME: github-actions-nginx
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: Docker Run
              run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest